appname="天朝局域网接入器"
appver="1.0"
appcode="1"
appsdk="15"
path_pattern=""
packagename="xyz.gkcoll.gfw.protester"
theme="Theme_Material_Light_NoActionBar"
app_key=""
app_channel=""
developer=""
description=""
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
